import Head from "next/head";
import Image from "next/image";
import PortfolioPic from "../public/images/portfolio-pic.jpg";
import Intro from "../components/Intro";
import ContactForm from "../components/ContactForm";
import AboutSection from "../components/AboutSection";
import { motion } from "framer-motion";
import styled from "styled-components";

export const ContactWrapper = styled.div`
  display: flex;
  // justify-content: center;
`;

export const ContactGrid = styled.div`
  border: solid 2px #000;
  margin: 65px;
  background: teal;
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-areas: "left right";
`;
export const LeftSide = styled.div`
  grid-area: left;
  // border-right: solid 1px #000;
`;
export const RightSide = styled.div`
  grid-area: right;
  // border-left: solid 1px #000;
  background: coral;
`;

const contact = () => {
  return (
    <>
      <Head>
        <title>Elsa Hovey | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3, duration: 0.5 }}
      >
        <h2>Contact Elsa</h2>
        <ContactWrapper>
          <ContactGrid>
            <LeftSide>
              <AboutSection />
            </LeftSide>
            <RightSide>
              <ContactForm />
            </RightSide>
          </ContactGrid>
        </ContactWrapper>
      </motion.div>
    </>
  );
};

export default contact;
