import Head from "next/head";
import Aside from "../components/Aside";
import { motion } from "framer-motion";
import WebsiteGrid from "../components/WebsiteGrid";
import ContactForm from "../components/ContactForm";

const Home = () => {
  return (
    <>
      <Head>
        <title>Elsa Hovey | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3, duration: 0.5 }}
      >
        <div className="grid 2xl:grid-cols-4 lg:grid-cols-1">
          {/* //* SECTION 1- MARGIN LEFT ADJUST */}
          <section id="index-margin" className="col-span-1 2xl:pr-4">
            <Aside />
          </section>

          {/* //* SECTION 2- MARGIN RIGHT ADJUST */}

          <section
            id="index-margin"
            className="bg-seasalt 2xl:col-span-3 lg:col-span-2 overflow-auto border-l border-b border-black lg:border-r-2 md:border-r-2 sm:border-r-2"
          >
            <div className="2xl:px-[100px] py-[20px] lg:pl-5 pr-5">
              <WebsiteGrid />
              <div className="2xl:w-1/2 sm:w-full p-5 mt-[150px]">
                <h2 className="text-3xl">Contact</h2>
                <p>
                  Has my portfolio piqued your interest....? If so, you can
                  contact me at devdesignsbyelsa@gmail.com Looking forward to
                  hearing from you!
                </p>
                <ContactForm />
              </div>
            </div>
          </section>
        </div>
      </motion.div>
    </>
  );
};

export default Home;
