/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Link from "next/link";
import { sanityClient, urlFor } from "../client";
import { motion } from "framer-motion";
import { AiFillGithub, AiOutlineLink } from "react-icons/ai";
import { Title } from "../components/styles/title.styled";
import { Flex } from "../components/styles/flex.styled";
import { Grid } from "../components/styles/grid.styled";
import Timeline from "../components/Timeline";
import Skills from "../components/Skills";
import { IntroSection } from "../components/styles/intro.styled";
import {
  PortfolioGrid,
  Sq,
  Button,
  IconWrapper,
  Icon,
} from "../components/styles/websites.styled";
import Contact from "../components/Contact";

const Home = ({ websites }) => {
  return (
    <>
      <Head>
        <title>Elsa Hovey- Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3, duration: 0.5 }}
      >
        <IntroSection>
          <p>
            I currently run two design studios: one catered to:
            <Link a href="https://writingtobetterhealth.com">
              registered dietitian nutritionists
            </Link>
            , and the other for:
            <Link href="/">small business owners and creatives.</Link>
          </p>
          <p style={{ paddingTop: "8px", fontSize: "22px" }}>
            Listed below, you can see all of my featured projects, read a little
            bit about me, or contact me... feel free to look around!
          </p>
        </IntroSection>
        {/* WORKS */}
        <Title id="works">Works</Title>
        <PortfolioGrid>
          {websites &&
            websites.map((website, index) => (
              <span key={index}>
                <Sq>
                  <Flex>
                    <h3>{website.websiteTitle}</h3>
                    <Icon>(i)</Icon>
                  </Flex>
                  <div>{website.description}</div>
                  <div>{website.tags}</div>
                  <Flex>
                    <Button>
                      <Link href={website.projectLink}>visit site</Link>
                      <IconWrapper>
                        <AiOutlineLink />
                      </IconWrapper>
                    </Button>
                    <Button>
                      <Link href={website.codeLink}>view code</Link>
                      <IconWrapper>
                        <AiFillGithub />
                      </IconWrapper>
                    </Button>
                  </Flex>
                </Sq>
              </span>
            ))}
        </PortfolioGrid>
        {/* ABOUT */}
        <Title id="about">About</Title>
        <p style={{ padding: "5px 50px", borderBottom: "solid 1px #000" }}>
          I currently work as a self-employed, indie web developer. Lorem ipsum
          dolor sit amet consectetur adipisicing elit. Reiciendis,
          necessitatibus cupiditate, dolore exceptu
        </p>
        <Grid>
          <Timeline />
          <Skills />
        </Grid>
        <Title id="contact">Contact</Title>
        <Contact />
      </motion.div>
    </>
  );
};
export default Home;

export const getServerSideProps = async () => {
  const query = '*[_type == "websites"] | order(_createdAt asc)';
  const websites = await sanityClient.fetch(query);
  if (!websites.length) {
    return {
      props: {
        websites: [],
      },
    };
  } else {
    return {
      props: {
        websites,
      },
    };
  }
};
